### PR TITLE
Trying to support combo item lavel/value style

### PR DESCRIPTION
**Pull request by sanak**
@moovida (CC: @dkastl, @mbasa-georepublic)  
This is trial implementation to enable https://github.com/moovida/smash/issues/107 feature.

### CODE REVIEW

**Comment by moovida** [comment]
Hi @sanak , thanks for the contribution, this looks good to me. 
I would only ask you to consider two things:

* add a section that showcases your addition in smash's example section: https://github.com/moovida/smash/blob/master/assets/tags.json . Between the combos and connectedcombos maybe add a "combos with item labels"?
* consider doing the same change to the connected combo section. Would that make sense for consistency or is that part to complicated?

**Comment by sanak** [comment]
@moovida (CC: @dkastl, @mbasa-georepublic, @iosefa)  
Thanks for confirmation!

> - add a section that showcases your addition in smash's example section: > https://github.com/moovida/smash/blob/master/assets/tags.json . Between the combos and connectedcombos maybe add a "combos with item labels"?

Yes, that's fine.
I will push another commit later, so please wait for a while.

> - consider doing the same change to the connected combo section. Would that make sense for consistency or is that part to complicated?

Well, I am still not familiar with connected combo and I don't know how to test it correctly, so I can't make this part quickly...
So, about this connected combo part, I would like to ask you to support this.

Thanks,

**Comment by sanak** [comment]
@moovida (CC: @dkastl, @mbasa-georepublic, @iosefa)  
Now I am trying to add example on `smash` side `assets/tags.json`, and I probably understand what connected combos meaning...

I will consider what structure is preferred with having consistency with stringcombo, so please wait for a while (about 1 day)...

**Comment by moovida** [comment]
Nice @sanak , thanks a lot. I will not be available today, but I will sure thing review and merge first thing tomorrow, if you have something.

**Comment by sanak** [comment]
@moovida  
Okay, thanks!

At this moment, just supporting `label`/`value` on `item` level may be the only possible pattern (to avoid complexity).
```js
"key": "two connected combos, default selected",
"values": {
    "items 1": [
        {"item": {""}, // => {"item": {"label": "", "value": "1-0"}}
        {"item": "choice 1 of 1"}, // => {"item": {"label": "choice 1 of 1", "value": "1-1"}}
        {"item": "choice 2 of 1"}, // => {"item": {"label": "choice 2 of 1", "value": "1-2"}}
        {"item": "choice 3 of 1"}, // => {"item": {"label": "choice 3 of 1", "value": "1-3"}}
        {"item": "choice 4 of 1"}, // => {"item": {"label": "choice 4 of 1", "value": "1-4"}}
        {"item": "choice 5 of 1"}  // => {"item": {"label": "choice 5 of 1", "value": "1-5"}}
    ],
    "items 2": [
        {"item": ""}, // => {"item": {"label": "", "value": "2-0"}}
        {"item": "choice 1 of 2"}, // => {"item": {"label": "choice 1 of 2, "value": "2-1"}}
        {"item": "choice 2 of 2"}, // => {"item": {"label": "choice 2 of 2, "value": "2-2"}}
        {"item": "choice 3 of 2"}, // => {"item": {"label": "choice 3 of 2, "value": "2-3"}}
        {"item": "choice 4 of 2"}, // => {"item": {"label": "choice 4 of 2, "value": "2-4"}}
        {"item": "choice 5 of 2"}  // => {"item": {"label": "choice 5 of 2, "value": "2-5"}}
    ]
},
"value": "items 2#choice 4 of 2", // => "value": "items 2#2-4"
"type": "connectedstringcombo"
```

Otherwise, some big schema changes will become necessary...
(The following is just my idea, but this will break present `tags.json` readability...)
```js
"key": "two connected combos, default selected",
"values": [
  {
    "label": "items 1",
    "value": "1",
    "items": [
      {"item": {"label": "", "value": "1-0"}},
      {"item": {"label": "choice 1 of 1", "value": "1-1"}},
      {"item": {"label": "choice 2 of 1", "value": "1-2"}},
      {"item": {"label": "choice 3 of 1", "value": "1-3"}},
      {"item": {"label": "choice 4 of 1", "value": "1-4"}},
      {"item": {"label": "choice 5 of 1", "value": "1-5"}}
    ]
  },
  {
    "label": "items 2",
    "value": "2",
    "items": [
      {"item": {"label": "", "value": "2-0"}},
      {"item": {"label": "choice 1 of 2, "value": "2-1"}},
      {"item": {"label": "choice 2 of 2, "value": "2-2"}},
      {"item": {"label": "choice 3 of 2, "value": "2-3"}},
      {"item": {"label": "choice 4 of 2, "value": "2-4"}},
      {"item": {"label": "choice 5 of 2, "value": "2-5"}}
    ]
  }
],
"value": "2#2-4",
"type": "connectedstringcombo"
```

Anyway, I will try to check whether above first case is actually possible by tomorrow.

**Comment by sanak** [comment]
Well, I was a bit busy with other task today...  
I will check this again, but it may take more hours.

**Comment by moovida** [comment]
Hi @sanak , I wonder if that is not getting too complicated. Maybe for now we should let the connected combos as they are?

**Comment by sanak** [comment]
@moovida 
> I wonder if that is not getting too complicated. Maybe for now we should let the connected combos as they are?

Oh, yes.
We become a bit busy with deliverable task in this week, so about connected combos, after next week is preferable for us...

**Comment by moovida** [comment]
Ok @sanak , let's put the connected combo aside and implement it later if there is need for it. I think it needs more thinking and a good usecase.

Could you just add an example to for the label+value type combo to this PR? I would then be happy to merge it in.

**Comment by sanak** [comment]
@moovida  
> Ok @sanak , let's put the connected combo aside and implement it later if there is need for it. I think it needs more thinking and a good usecase.

Okay, thanks. 🙇‍♂️ 

> Could you just add an example to for the label+value type combo to this PR? I would then be happy to merge it in.

Well, I thought that the PR will be for `smash` side's `assets/tags.json` modification, but is that okay ?

**Comment by moovida** [comment]
@sanak , sure, sorry, I made a bit of confusion. That one goes to the SMASH repo :-)

Ok, will merge this here in the meanwhile, thanks

**Comment by sanak** [comment]
@moovida Okay, thanks! 🙇‍♂️

**Pull request merged**
